# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(blank=True, related_name='casting', to='api.Actor'),
        ),
    ]
