# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170325_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
