# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170504_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='poster',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
