# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_actor_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='poster',
            field=models.CharField(default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='writer',
            name='poster',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
